<?php
/** Zend_Controller_Action */
require_once 'Zend/Controller/Action.php';
require_once 'Zend/Db.php';
require_once 'Zend/Debug.php';

class DbController extends Zend_Controller_Action
{
	public function init()
	{
		$this->db = Zend_Db::factory(Zend_Controller_Front::getInstance()->getParam('config')->database);
	}
	
    public function indexAction()
    {
    	Zend_Controller_Front::getInstance()->getParam('auth')->auth(1);
    	// All
    	$sql = 'SELECT ID, name FROM Page';
		$result = $this->db->fetchAll($sql);
		
		$this->view->table = $result;
    }

    public function addAction()
    {
    	Zend_Controller_Front::getInstance()->getParam('auth')->auth(9);
    	// Render 'form.phtml' instead of 'add.phtml'
        $this->_helper->viewRenderer('form');
    }

    public function editAction()
    {
		Zend_Controller_Front::getInstance()->getParam('auth')->auth(9);
    	$id = $this->_getParam('id', 0);
    	
    	// Only one ID
    	$sql = 'SELECT name, body 
    			FROM 
    				Page 
    				INNER JOIN Text on Page.Text_ID = Text.ID
    			WHERE Page.ID = ?';
		$result = $this->db->fetchAll($sql, $id);
		$this->view->id = $id;
		$this->view->name = $result[0]['name'];
		$this->view->content = $result[0]['body'];

		// Render 'form.phtml' instead of 'edit.phtml'
        $this->_helper->viewRenderer('form');
    }

    public function delAction()
    {
    	Zend_Controller_Front::getInstance()->getParam('auth')->auth(9);
        $id = $this->_getParam('id', 0);
    	
    	// delete
		$result = $this->db->delete('Page', "ID = $id");

		// display List
		$this->_helper->viewRenderer('index');
		$this->indexAction();
    }
    
    public function viewAction()
    {
    	Zend_Controller_Front::getInstance()->getParam('auth')->auth(1);
    	$id = 	$this->_getParam('id', 0);
    	// do some validation...
        if ( $id == 0) {
        	// Return to Index
        	$this->_helper->viewRenderer('index');
        	$this->indexAction();
        }
        else {
        	// Display page
        	$this->view->id = $id;
	    	// Only one ID
	    	$sql = 'SELECT name, body 
	    			FROM 
	    				Page 
	    				INNER JOIN Text on Page.Text_ID = Text.ID
	    			WHERE Page.ID = ?';
			$result = $this->db->fetchAll($sql, $id);
			$this->view->id = $id;
			$this->view->name = $result[0]['name'];
			$this->view->content = $result[0]['body'];
        }
        return;
    }
    
    public function processAction()
    {
    	Zend_Controller_Front::getInstance()->getParam('auth')->auth(9);
        $id = 	$this->_getParam('id', 0);
    	$name = $this->_getParam('name', '');
        $text = $this->_getParam('text', '');
		$this->view->name = $name;
		$this->view->content = $text;
        
        // do some validation...
        if ( ($id == 0) or ($name == '') or ($text == '') ) {
			$this->view->id = $id;
			$this->view->msg = 'One or more fields are not filled!';
            $this->editAction();
            return;
        }
		if ($id != 0) {
			$sql = 'SELECT Text_ID FROM	Page WHERE ID = ?';
			$result = $this->db->fetchAll($sql, $id);
			$text_id = $result[0]['Text_ID'];
		}
		else {
			$text_id = 0;
		}
        
        // otherwise continue processing...
        $data = array(
        	'ID'			=> $text_id,
    		'Msg_ID' 		=> 0,
    		'content_type' 	=> 'text/html',
    		'body' 			=> $text,
			);
		$this->InsertOrUpdate('Text', array('ID'), $data);
    	if ($text_id == 0) {
    		$text_id = $this->db->lastInsertId();
		}
		
		$data = array(
        	'ID'		=> $id,
    		'name' 		=> $pic,
    		'Text_ID' 	=> $text_id,
    		'username' 	=> Zend_Controller_Front::getInstance()->getParam('auth')->username,
        	'modify'	=> new Zend_Db_Expr('CURDATE()')
			);
		$this->InsertOrUpdate('Page', array('ID'), $data);
		
		// return the last value generated by an auto-increment column
		if ($id != 0) {
			$this->view->id = $id;						
		}
		else
		{
			$this->view->id = $this->db->lastInsertId();
		}
		
		$this->_helper->viewRenderer('view');
		
		return;
    }
    
    private function InsertOrUpdate($table, $PrimKey, $data)
    {
    	$sql = "SELECT COUNT(*) FROM $table WHERE ";
    	$where = array();
    	$and_bit = false;
    	foreach ($PrimKey as $key) {
    		if ($and_bit)
    		{
    			$sql .= ' and ';
    		}
    		$sql .= "$key = '" . $data[$key] ."'";
    		$where[] = "$key = '" . $data[$key] ."'";
    		$and_bit = true;
    	}
		
    	if ($this->db->fetchOne($sql) == 0 )
    	{
    		//insert
    		Zend_Controller_Front::getInstance()->getParam('auth')->auth(2);
    		$this->db->insert($table, $data);
    	}
    	else
    	{
    		//update
    		Zend_Controller_Front::getInstance()->getParam('auth')->auth(3);
    		$this->db->update($table, $data, $where);
    	}
    }
}


?>
