    <?php
    	echo "<p>Hi " . $this->escape($this->realname) . "!</p>\n";
    	echo "<p>You have clearance level " . $this->escape($this->level) . ".</p>";
    ?>
    
    <p>There are 10 different clearance levels at the moment:</p>
    <ul>
	  <li><b>0</b> Unauthorizesed access. Everything is forbitten.</li>
	  <li><b>1</b> Entry level for new users. You may view the most of the content. Infos about other users is hidden.</li>
	  <li><b>2</b> You have contributed some pics or messages to this database through one of the monitored groups or directly. You may view all the content including the infos about other users.</li>
	  <li><b>3</b> You were approved to be valueable. You may now suggest tags and connections</li>
	  <li><b>4</b> You were approved to be a good. Your tags and connections are automaticly approved.</li>
	  <li><b>5</b> You were approved to be a worthy. Your may approve tags and connections from other users.</li>
	  <li><b>6</b> A good number, but the way here is the goal.</li>
	  <li><b>6</b> Yes, you are slowly entering the spheres of heaven. You can almost here the harps play.</li>
	  <li><b>8</b> You got it. You are a developer. You will know what to do.</li>
	  <li><b>9</b> You are a godlike, unreachable, fabulous. You are a being of light and good will. You know what you do. Yes, I think this level is reserved for me only.  :-)</li>
	</ul>

