<?php 
if ($this->image == null) {
	echo "	<p>No Image here</p>";
}
else {
	// Table begin
	echo "	<table border=1>\n";
	
	// Table Header
	
	echo "	<tr>\n";
	$image = $this->image;
	echo '		<td><img src="' . $this->escape($image->url) . '"><br>' . $this->escape($image->origfilename) .	"<br>\n";
	foreach ($image->tags as $tag) {
		echo '<a href="/browse/imgtable?q='.$this->escape($tag->name).'">'.$this->escape($tag->name).'</a> ';
	}
	echo "		</td>\n";
	echo "	</tr>\n";
	
	// Table end
	echo "	</table>\n";
} // if ($this->image == null)
?>