	<h1>Do it yourself corner</h1>

	<p>So you want to do more than just looking around. Great we can need your help. 
	But. Yes there is always a "but". Clearance level 2 is need for the most tasks here.</p>
	
<?php
	if ($this->level >= 3) {
		echo '<p>You are ' . $this->escape($this->realname) . ' and you have clearence level ' . 
			$this->escape($this->level) . '. You should have no problems accessing the most of the functions here.</p>';
?>
	<p>You can start to tag the images in this database, by clicking "Tags -&gt; Tagging" from the toplevel menu.</p> 
<?php
	}
	else {
		echo '	<p>You are ' . $this->escape($this->realname) . ' and you have clearence level ' . 
			$this->escape($this->level) . ". I'm afraid that is too low for many of the functions here.</p>\n";
?>
	<p>But this not the end. Just go <a href="/index/level">here</a> and lern how to increase your clearence level!</p> 
<?php
	}
?>

