<?php 

//echo "<pre>",print_r($this->msg);echo "</pre>";

if ($this->msg == null) {
	echo "	<p>No Msg here</p>";
	//TODO: Someone should add a kind of advanced search options for the messages to be tagged
}
else {
?>
	<script type="text/javascript" src="dhtml.js"></script>
	<script type="text/javascript">
		var All_Tags = new Array (<?php
			//TODO: Add all Tags here 
			echo "'Latex', 'Bianca', 'toSave', 'asd', 'Latex on Mars'"; 
		?>);
		
		<?php 
		//TODO: Add Up- and Down-Key support for the Suggestions 
		?>
		function Add_Tag(input, destination, readable) {
			<?php
			// TODO: Check is already there
			?>
			destination.value = destination.value + input.value + ';';
			input.value = '';
			UpdateReadable(destination, readable);
		}
		
		function Remove_Tag(destination, tag_name, readable) {
			var tags = '';
			var tags_string = destination.value;
			var tags_array = tags_string.split(';');
			tag_name = decodeURI(tag_name);
			for ( var tag_n in tags_array ) {
				tag = tags_array[tag_n];
				if (tag != '' && tag != tag_name)
					tags = tags + tag + ';'; 
			}
			destination.value = tags;
			UpdateReadable(destination, readable);
		}
		
		function UpdateReadable(destination, readable) {
			var tags = '';
			var tags_array = destination.value.split(';');
			for ( var tag_n in tags_array ) {
				tag = tags_array[tag_n];
				if (tag != '')
					tags = tags + tag + '(<a href="JavaScript:Remove_Tag(document.form1.' + destination.name + ',\'' + encodeURI(tag) + '\', \'' + readable + '\')";>X</a>) '; 
			}
			getElement("id", readable, null).innerHTML = tags;
		}
		
		function Change_Input(input, tag_name) {
			input.value = decodeURI(tag_name);
		}
		
		function SuggestTag(input, destination, readable, suggest) {
			if (input.value == '') {
				getElement("id", suggest, null).innerHTML = '';
			}
			else {
				var tags = '';
				for ( var tag_n in All_Tags ) {
					tag = All_Tags[tag_n];
					if (tag.toLowerCase().indexOf(input.value.toLowerCase()) != -1) {
						tags = tags + 
							' <a href="JavaScript:' +
								'Change_Input(document.form1.' + input.name + ', \'' + encodeURI(tag) + '\');' + 
								'Add_Tag(document.form1.' + input.name + ',document.form1.' + destination.name + ', \'' + readable + '\');' + 
								'SuggestTag(document.form1.' + input.name + ',document.form1.' + destination.name + ', \'' + readable + '\', \'' + suggest + '\');' + 
							'">' + tag + '</a><br>'; 
					}
				}
				getElement("id", suggest, null).innerHTML = tags;
			}
		}
	</script>


	<form name="form1" action="/tags/process" method="post">
	<table border=1>
	
		<tr>
			<td>From: <?php echo $this->escape($this->msg->sender); ?><br>
			Date: <?php echo $this->escape($this->msg->date); ?><br>
			Subject: <?php echo $this->escape($this->msg->subject); ?></td>
		</tr>

		<tr>
			<td>Tags:
			<div id="msg_tags_readable">&nbsp;</div>
			<input type='hidden' name='msg_tags' value='<?php
				// TODO: Display current Tags 
    		    // TODO: Suggest Tags based on low level users and from keyword searching (subject/body matches tagname, ...)
				echo "Bianca;Latex;";
			?>'>
			<input type='hidden' name='msg_id' value='<?php
				echo $this->escape($this->msg->ID);
			?>'>
			<input type='text' name='msg_tag' value='' size=32 onKeyup="SuggestTag(document.form1.msg_tag, document.form1.msg_tags, 'msg_tags_readable', 'msg_tags_suggestion')">
			<input type='submit' value='Add' onClick="Add_Tag(document.form1.msg_tag, document.form1.msg_tags, 'msg_tags_readable'); return false;">
			<div id="msg_tags_suggestion" class="Navi_menu">&nbsp;</div>
			<script type="text/javascript"> 
				UpdateReadable( document.form1.msg_tags, 'msg_tags_readable');
				SuggestTag(document.form1.msg_tag, document.form1.msg_tags, 'msg_tags_readable', 'msg_tags_suggestion');
			</script>
			</td>
		</tr>

		<tr>
			<td>
<?php 
// Image Table

	if ($this->msg->images != null) {
		// Table begin
		echo "		<table border=1>\n";
		
		// Table Header
		
		// Cell loop
		$count = 0;
		echo "		  <tr>\n";
		foreach ($this->msg->images as $image) {
			echo '			<td align="center" valign="bottom"><a href="/browse/image?ID=' .$this->escape($image->ID). '">';
			if (isset($image->urlthumb)) {
				echo '<img src="' . $this->escape($image->urlthumb) . '"><br>';
			}
			echo $this->escape($image->origfilename) . "</a><br>";
			foreach ($image->tags as $tag) {
				echo '<a href="/browse/imgtable?q='.$this->escape($tag->ID).'">'.$this->escape($tag->name).'</a> ';
			}
			echo "</td>\n";
			$count++;
			if ($count == 3) {
				echo "		  </tr>\n		  <tr>\n";
				$count = 0;
			}
		}
		echo "		  </tr>\n";
		
		// Table end
		echo "		</table>\n";
		
	} // if ($obj->images == null)


?>
			</td>
		</tr>
		
<?php 
	foreach ($this->msg->texts as $text) {
		echo '	<tr></td>'.$this->escape($image->content_type)."</td></tr>\n";
		echo "	<tr>\n		</td>".$this->escape($image->body)."</td>\n	</tr>\n";
	}
	//echo "	<tr>\n		<td>".$this->formSubmit('submit')."</td>\n	</tr>\n";
?>

	</table>
	<input type='submit' name='add_tag' value='Save Changes'>
	</form>
<?php
} // if ($this->msg == null)
?>