<?php 
require_once('functions_imgtable.phtml');

if ($this->msg == null) {
	echo "	<p>No Msg here</p>";
}
else {
	// Table begin
	echo "	<table border=1>\n";
	
	echo "	<tr>\n";
	echo "		<td>From: " . $this->escape($this->msg->sender) . "<br>";
	echo "Date: " . $this->escape($this->msg->date) . "<br>";
	echo "Subject: " . $this->escape($this->msg->subject) . "<br>";
	echo "</td>\n";
	echo "	</tr>\n";

	echo "	<tr>\n";
	echo "		<td>";
	imgTable($this->msg, $this);
	/*foreach ($this->msg->images as $image) {
		echo '<a href="/browse/image?ID='.$this->escape($image->ID).'">'.$this->escape($image->origfilename).'</a> ';
	}*/
	echo "</td>\n";
	echo "	</tr>\n";

	foreach ($this->msg->texts as $text) {
		echo '	<tr></td>'.$this->escape($image->content_type)."</td></tr>\n";
		echo "	<tr>\n		</td>".$this->escape($image->body)."</td>\n	</tr>\n";
	}
	
	// Table end
	echo "	</table>\n";
} // if ($this->msg == null)

?>