<?php
function tagCloud($tags, $_this) {
	if ($tags == null) {
		return false;
	}
	else {	
		foreach ($tags as $cat => $tags) {
			echo "<h2>".$_this->escape($cat)."</h2>\n<p>";
			// change these font sizes if you will
			$max_size = 200; // max font size in %
			$min_size = 25; // min font size in %
			
			// get the largest and smallest array values
			$max_qty = log(max(array_values($tags->tags)),1.5);
			$min_qty = log(min(array_values($tags->tags)),1.5);
			
			// find the range of values
			$spread = $max_qty - $min_qty;
			if (0 == $spread) { // we don't want to divide by zero
			    $spread = 1;
			}
			
			// determine the font-size increment
			// this is the increase per tag quantity (times used)
			$step = ($max_size - $min_size)/($spread);
			
			// loop through our tag array
			foreach ($tags->tags as $key => $value) {
			
			    // calculate CSS font-size
			    // find the $value in excess of $min_qty
			    // multiply by the font-size increment ($size)
			    // and add the $min_size set above
			    $size = $min_size + ((log($value,1.5) - $min_qty) * $step);
			    // uncomment if you want sizes in whole %:
			    // $size = ceil($size);
			
			    // you'll need to put the link destination in place of the #
			    // (assuming your tag links to some sort of details page)
			    echo '<a href="/browse/imgtable?q='.$_this->escape($key).'" style="font-size: '.$size.'%"';
			    // perhaps adjust this title attribute for the things that are tagged
			    echo ' title="'.$_this->escape($value).' things tagged with '.$_this->escape($tags->names[$key]).'">'.$_this->escape($tags->names[$key]);
			    if ($tags->score[$key]) {
			    	echo ' ('.$_this->escape($tags->score[$key]).')';
			    }
			    echo '</a> ';
			    // notice the space at the end of the link
			}
			echo "</p>";
		}
	} // $tags == NULL
}
?>