    <h2>Input Form</h2>
    <?php
        if ($this->msg != '') {
            echo "<p>" . $this->escape($this->msg) . "</p>";
        }
    ?>
    
    <form action="/browse/search" method="post">
    	<p>Type: <?php 
    	
    	$options = array(
    		'' 			=> 'All',
    		'Images' 	=> 'Images',
    		'Msgs' 		=> 'Messages',
    		'Tags' 		=> 'Tags'
    	);
    	echo $this->formSelect('type', '', '', $options); 
    	
    	?><br>
    	Search: <?php echo $this->formText('q'); ?> 
        <?php echo $this->formSubmit('submit'); ?></p>
    </form>
