<?php 
if ($this->images == null) {
	echo "	<p>No Images here</p>";
}
else {
	// Table begin
	echo "	<table border=1>\n";
	
	// Table Header
	
	// Cell loop
	$count = 0;
	echo "	<tr>\n";
	foreach ($this->images as $image) {
		echo '		<td><a href="browse/image?ID=' .$this->escape($image->ID). '"><img src="' . $this->escape($image->urlthumb) . '"><br>' . $this->escape($image->origfilename) . "</a></td>\n";
		$count++;
		if ($count == 3) {
			echo "	</tr>\n	<tr>\n";
			$count = 0;
		}
	}
	echo "	</tr>\n";
	
	// Table end
	echo "	</table>\n";
} // if ($this->images == null)
?>