<?php
require_once('functions_imgtable.phtml');
require_once('functions_msgtable.phtml');
require_once('functions_tagcloud.phtml');


if ($this->imagemsg != '') {
	echo "<p>" . $this->escape($this->imagemsg) . "</p>";
}

imgTable($this->images, $this);


if ($this->tagmsg != '') {
	echo "<p>" . $this->escape($this->tagmsg) . "</p>";
}

tagCloud($this->tags, $this);


if ($this->msgmsg != '') {
	echo "<p>" . $this->escape($this->msgmsg) . "</p>";
}

msgTable($this->msgs, $this);

?>